name: Build Android APK

on:
  push:
    branches: [ "truockhibuild" ] # Chạy tự động khi có code mới trên nhánh này
  workflow_dispatch: # Cho phép bấm nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Flutter mới thường dùng Java 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0' # Phiên bản ổn định

      - name: Get Dependencies
        working-directory: ./frontend/mobile_web_flutter
        run: flutter pub get

      - name: Build APK
        working-directory: ./frontend/mobile_web_flutter
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: frontend/mobile_web_flutter/build/app/outputs/flutter-apk/app-release.apk
